### ISSUE TITLE
Failed to remove row

### ISSUE THREAD

**Issue by rastermanden** [danioxoli/HotSpotAnalysis_Plugin#1]
When I run Local Getis-Ord Gi* with other settings like when checking "Use Knn standardized spatial weights" I get an error in Distance.py line 112 in "row.remove(i)". The error is caused by "i not in row array".
[error.zip](https://github.com/danioxoli/HotSpotAnalysis_Plugin/files/1295767/error.zip)

```python
        neighbors = {}
        for i,row in enumerate(to_weight):
            row = row.tolist()
            row.remove(i) #This line (112) gives error 
            row = [ids[j] for j in row]
            focal = ids[i]
            neighbors[focal] = row
        W.__init__(self, neighbors, id_order=ids)
```

Any suggestions ?

**Comment by danioxoli** [comment]
Hi!
I have tested your shapefile with the knn. Actually I have found that a bunch of points share the same position (somewhere offshore to Guinea: ![screen0](https://user-images.githubusercontent.com/15163569/30330282-f1e391d4-97d4-11e7-8921-1c59961f1f6d.jpg)

Actually, the Hotspot analysis does not deal with single location associated to multiple point geometries. Probably, the index is out of the array as it should store only pairwise positive distances computed between different locations (the Distance.py is an external command used by Scipy, I don't know much about it, you can try to dig into at: [distance.py](https://github.com/scipy/scipy/blob/master/scipy/spatial/distance.py)) 

Removing these duplicated points the plugin works:

![screen2](https://user-images.githubusercontent.com/15163569/30330582-c55b219e-97d5-11e7-8bde-64e365e8073a.jpg)

![screen1](https://user-images.githubusercontent.com/15163569/30330575-c138c2b0-97d5-11e7-8fa4-59a22a173eb2.jpg)


Let me know if the the issue is solved!

Daniele

**Comment by rastermanden** [comment]
It works for me also! Thank you very much.
