### ISSUE TITLE
QGIS plugin not loading: no module named pysal

### ISSUE THREAD

**Issue by biancaglez** [danioxoli/HotSpotAnalysis_Plugin#2]
QGIS plugin not loading on Mac 10.12.4 : "No module named pysal" with QGIS 2.18, pysal PySAL 1.14.2, scipy version 0.19.1 and numpy version 1.13.3.

Any recs on how to fix?

**Comment by danioxoli** [comment]
Dear Bianca

Thank you for your interest in the plugin. Unfortunately, dependencies issue are difficult to fix form remote as are normally due to local settings. Have you tried to check if your libraries are recognized by QGIS? 

For instance, you can try to type:
**import pysal**
in the  QGIS Python console and see if no error comes out.

Have you installed the dependencies using the **pip** or using the binary from [http://www.kyngchaos.com/software/python](http://www.kyngchaos.com/software/python)?
This does not usually influence the outcomes using macOS but just be sure that you import the libraries in the same Python environment of you QGIS.

Let me know if you will manage to solve the problem!

Daniele

**Comment by biancaglez** [comment]
Hi Daniele, 

I have tried pip and installing pysal. Would you happen to know how to check if these libraries are recognized by QGIS? 

-Bianca

**Comment by danioxoli** [comment]
Hi Bianca,

You may open QGIS and activate  the QGIS Python console (http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/intro.html). Then just type in the console:
**import pysal**
and press enter.

If no errors are displayed that means the library is recognized by QGIS.

Best,

Daniele

**Comment by ericnost** [comment]
Hello,

I am having the same problem. I receive the following error when checking **import pysal**

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named pysal

I did however install pysal through **sudo easy_install pysal** though apparently in the wrong environment. Do you have any thoughts on how to install it in the proper environment? I do not remember how I originally installed QGIS.

Very grateful,

Eric

**Comment by danioxoli** [comment]
Dear Eric and Bianca,

Plase find in the following links some useful hints regarding QGIS Python features on macOS:

a) https://gis.stackexchange.com/questions/181858/installing-python-xlw-and-xlrd-libraries-for-qgis-on-mac-osx-with-python-2-6?rq=1

b) https://gis.stackexchange.com/questions/242338/adding-python-module-to-qgis-python-interpreter-on-mac

c) http://carlosgrohmann.com/fixing-python-path-for-qgis-scripting-on-mac-osx/

Hope you are going to solve the issue asap.

Best,
Daniele

**Comment by JirkaPanek1** [comment]
Dear Eric, I have the same issue, but on Windows, I have QGIS 2.18.14, have instaled PySAL via OSGeo4W, but I am getting this bug:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named pysal

any ideas, what to do about it?

Thanks

Jirka

**Comment by danioxoli** [comment]
Dear Jarika,

On Windows there is a third possibility to install Pysal (not really suggeted but usually it works). It is described in the installation instruction within the readme file.

Basically, you have to open this folder:

C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages

Remove (if exist) any folder of Pysal.

Download and decompress the folder you can download form here:

https://pypi.python.org/packages/e7/3b/af87cd60f03734897caa6dc3e840fc10458d0a2c060b3d71803dc56992db/PySAL-1.13.0.tar.gz

Inside there is a subfolder called “pysal”

copy it directly inside the aforementioned folder path.

If both numpy and scipy are correctly installed there, you should be able to use the plugin as well as pysal from QGIS.

Best,

Daniele

**Comment by JirkaPanek1** [comment]
Dear Deniele, 
thank you, that trick worked!
Jirka

**Comment by gp86041** [comment]
I am having the same problem. I checked the pysal is installed in my terminal, but QGIS keeps saying "No module named pysal". Yet, I can successfully import pysal in mac terminal. Anyone please help..

**Comment by danioxoli** [comment]
Dear Jeff,

Did you try to import Pysal directly from the python shell of QGIS? 
If within the software the library is not recognized while from the terminal it is, this might be a problem of your python environment, i.e. you have installed the library with pip in a different python path than the one used by QGIS.

Let me know! 
Daniele

**Comment by gp86041** [comment]
I have adjusted the path and now in my terminal, I can `import qgis.core` correctly. Yet, in Qgis, it still does not recognize that I have the pysal module. The detailed error message is below:

==================
Couldn't load plugin HotSpotAnalysis_Plugin due to an error when calling its classFactory() method 

ImportError: No module named pysal 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/gepu/.qgis2/python/plugins/HotSpotAnalysis_Plugin/__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/gepu/.qgis2/python/plugins/HotSpotAnalysis_Plugin/hotspot_analysis.py", line 31, in 
    import pysal
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named pysal
=======================

In Qgis, when I type in `import pysal` in concole, it gives me the error below:

=======================
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named pysal
=======================

**Comment by danioxoli** [comment]
Working with Mac and installing Pysal via `sudo easy_install pysal` 

This should be the location where QGIS looks for Python libraries:
`/Library/Python/2.7/site-packages`

If you work under Anaconda (https://www.anaconda.com), using `pip install pysal`, instead:
` /Users/<your user name>/anaconda/lib/python2.7/site-packages`
(this second option works for me, I strongly suggest Anaconda) 

Try this on both terminal and QGIS shell:
`import sys
print sys.path`

This will reveal where your Python is looking for libraries. It might be that QGIS does not look into one of the above locations. With Mac, QGIS should use the native Python distribution of your OS. If this is not true for you, you might try to impose an [order of importation] from different paths.

Hope this will help!

Daniele

[order of importation]:<https://gis.stackexchange.com/questions/80239/how-to-set-pythonpath-in-os-x-to-use-pyqgis>

**Comment by ChrisUKGIS** [comment]
Hello,

I am using windows and I was having the "No module named pysal" issue. I have tried using the other methods, and the one here (http://quantumofgis.blogspot.co.uk/2014/11/qgis-standalone-and-python-modules.html) to install pysal but they did not work. The third method of installing pysal (copying the directory into the main folder) did work but not completely. The error message has now changed to:
****************************************************************

Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pysal\__init__.py", line 40, in <module>
    import pysal.cg
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pysal\cg\__init__.py", line 4, in <module>
    from shapes import *
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'shapes'

******************************************

Any help much appreciated.

**Comment by danioxoli** [comment]
Dear Chris,

This is the only way I found so far to solved the issue on Windows.

go to: `C:\Program Files\QGIS 3.0\apps\Python36\Scripts`
unzip: `pip3.exe` 

Open the OSGeo4W as administator and type:
`python "C:\Program Files\QGIS 3.0\apps\Python36\Scripts\__main__.py" install pysal`

Hope this will work also for you. Let me know!

Daniele

**Comment by ChrisUKGIS** [comment]
Thanks for the rapid response!

I tried it but it says "[Errno 2] No such file or directory"

I don't have a "_main_. Py" file.

My python default is set to 3.6.0 64bit.

🤔

**Comment by danioxoli** [comment]
Did you check if the `__main__.py` actually appear in the folder after decompressing (with 7zip maybe) the `pip3.exe`?

I know that this is not the proper way of installing but I tested it again on a Windows 10 VM and It was working. Alternatively you can try to write [here](https://www.qgis.org/it/site/getinvolved/mailinglists.html) to see if someone else have faced this issue with QGIS3 yet. 

Best
Daniele

**Comment by ChrisUKGIS** [comment]
No " __main__.py " appeared in the folder. The file pip3.exe is not  compressed, it was already in the Scripts folder. I just double clicked it.

I have used get-pip.py, and it has uninstalled pip version 9 and installed version 10.
Used "pip install -U pysal" and it worked, previously it didn't recognise the command.

I'll update this post if there are any other problems but I think it should be plain sailing from now on!

👍

**Comment by krispiepage** [comment]
I am also having problems loading pysal into qgis, I have tried countless times, how exactly do you ensure you are installing scipy numpy and pysal directly into the python used in qgis?

**Comment by danioxoli** [comment]
QGIS on MAC OSx uses the Python system installation.

If you are using QGIS3 you must specify during the PySAL installation the Python version (Python 3 in this case). 

Did you have a look at the correct documentation in the readme file? Please, notice that installation patterns vary from QGIS2 ([master](https://github.com/danioxoli/HotSpotAnalysis_Plugin/tree/master)) and QGIS3 ([branch](https://github.com/danioxoli/HotSpotAnalysis_Plugin/tree/qgis3)) versions.

I actually use the [Anaconda](https://www.anaconda.com/distribution/) Python distribution if this can help.

Best,

Daniele

**Comment by danioxoli** [comment]
Definitely, try with [Anaconda](https://www.anaconda.com/distribution/) on Mac.
After installing it, just open a terminal and type: 
`conda install -c anaconda pysal `
and let me know!

Best,
Daniele

**Comment by krispiepage** [comment]
Hi anaconda managed to install pysal!

but when I download the hotspot plug in it still says pysal is missing within qgis? :/ 

Ive checked the system for where pysal has been installed and its in the anaconda file path, how does the qgis python system know to look here for the module?

**Comment by krispiepage** [comment]
Just to let you know I managed to crack it, I removed anaconda,

I then used sudo easy install pip
then pip install pysal

i made the mistake trying to get pip to be installed by downloading the the get pip file but didnt maange to install it correctly.

So sorry for being so un foresighted.

Thanks for you help danielle.

**Comment by krispiepage** [comment]
Daniele,

I was just wondering if you could help me with the hotspot plugin, I have some point data I am trying to do some hotspot analysis with I'm trying to run the plugin but I get this error:

Traceback (most recent call last):
			  File "/Users/cspage/.qgis2/python/plugins/HotspotAnalysis/hotspot_analysis.py", line 620, in run
			    statistics = G_Local(y, w, star=True, transform=type_w, permutations=permutationsValue)
			  File "/Library/Python/2.7/site-packages/pysal/esda/getisord.py", line 352, in __init__
			    self.calc()
			  File "/Library/Python/2.7/site-packages/pysal/esda/getisord.py", line 403, in calc
			    y2 = y * y
			TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'
			

Have you got any ideas what could be going wrong?

**Comment by danioxoli** [comment]
Yes, actually this should be due by one of the following input layer mistakes:

A) you are using a virtual field as input attribute e.g. a field coming from a join operation. Remember  that the attribute for the analysis must belong to the shapefile attribute table. In this case you need to save a copy of the input shapefile and use this for the analysis.
B) you are using a string attribute instead of a numeric one. In this case just format a new field and convert your strings into numbers
C) your field contains NULL values. This is not accepted by the PySAL function used to compute the Gi*. In this case you need to fill NULL or remove from the shapefile the fatures with empty attributes.

Hope this will help you!

Daniele

**Comment by rfernan6ASU** [comment]
Hi Danielle, I had the no "No module named pysal" at first. I followed your recommendation to download anaconda and I think I already installed pysal in the proper environment (i.e. py 3.6). Yet, I keep getting an error while trying to open the hotspot plugin:  

Couldn't load plugin 'HotspotAnalysis' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'pysal.esda' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/Rafael/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/Rafael/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/hotspot_analysis.py", line 39, in 
    from pysal.esda.getisord import *
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pysal.esda'


Python version: 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.4.4-Madeira Madeira, exported

**Comment by danioxoli** [comment]
Which version of PySAL did you install?
Unfortunately, the plugin does not work currently with the latest release (2.0). You need to downgrade to the 1.4 version (e.g. 1.4.3).

Let me know if this will solve the problem.

Best,

Daniele

**Comment by rfernan6ASU** [comment]
I used the last one (2.0). However, I just installed  pysal 1.14.4
![image](https://user-images.githubusercontent.com/47647746/52873878-aabb8100-3115-11e9-822b-521c47ca97e5.png)

I still can't use the plugin. 

![image](https://user-images.githubusercontent.com/47647746/52874358-eacf3380-3116-11e9-99d7-c7edd963bf65.png)

Is there any way to tell Qgis to use a specific environment, for this case python 2.6 or 2.7, and the specific version 1.14 of pysal? 

in the error dialogue, It looks like is calling python 3.6. 

/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/Rafael/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/Rafael/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/D/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/Rafael/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/Rafael/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/Users/Rafael/Desktop/ACADEMIA/UBC posdoc/Datos/Naturalista

I'm sorry if I am asking something way too simple or redundant. I'm new to both QGIS and all this python universe. 

I like it so far. 

Thank you for yer help! 

Cheers,

Rafa

**Comment by danioxoli** [comment]
On Mac, the py version should be 3.6.

I suggest you to try the standard installation thet is suggested in the [readme](url
https://github.com/danioxoli/HotSpotAnalysis_Plugin/blob/qgis3/README.md) file of the QGIS3 branch (i.e. using the pip) before going for Ananconda.

I use PySAL 1.14.3 on my machine and I test it on a QGIS3.2 distribution.

As soon as I’ll find time I’ll go through the QGIS3.4 and the Pysal 2.0 to check what may cause this issues.

Daniele

**Comment by rfernan6ASU** [comment]
Dear Daniele, 

I just tried again using the read me file you recommended and it worked. My sincere apologies for being so feeble minded and not following the instructions from the beginning. My bad. 

The plugin is installed and I'll start experimenting with it. 

Have a great week!

Cheers,

Rafa
