### ISSUE TITLE
result show contradict hotspot analysis from Arcmap

### ISSUE THREAD

**Issue by Ariel505** [danioxoli/HotSpotAnalysis_Plugin#3]
Hi, 
I newly tryout hotspot analysis from this qgis plugin and I also run the same dataset in Arcmap.
But they show different mapping result.
Getis-Ord Gi value also different for each polygon. with FIX-DISTANCE-BAND
You may find dataset here:
https://goo.gl/GFPJp4
Here I use the field: (SUMME) to analysis hot and cold spot.
Not sure if this error come from negitive value from the data.

You can also see the screenshot of comparison result from ArcMap and QGIS:
https://goo.gl/NtmweZ

It seems to me that the result were contradict, that some area in Arcmap shows hotspot (red) but from QGIS plugin it shows coldspot (blue).

Please see if you also have the same result and if this can be fixed?
Thanks.

Best Regards,
Ariel

**Comment by danioxoli** [comment]
Dear Ariel,

Thank you for your interest. Yes, negative values produce some trouble as the procedure of the plugin is based on the Pysal Gi* (which implement the original statistic that accepted only positive values). I did work on that in order to enable the use of negative values. However, I tested that against ArcGIS only on a limited set of cases.
What I faced with ArcMap was a not clear distinction between significance testing that is there implemented. It seems that it does not actually use a random permutation approach but it computes pseudo p values against normality assumption only. For this reason, the default method used by my plugin is exactly based on the normality assumption.
If vice-versa the random permutation is adopted, some minor changes can be due to the random generator which likely does not produce equal results (but this should not be so relevant to your case)

What I do not understand is the use of the FIX-DISTANCE-BAND for a polygon layer. The plugin is programmed to use a queen's case spatial weight matrix (or edges and corners contiguity in ArcMap) when fed with a polygon layer. This might be the main reason for the difference.
Can you try this way on ArcMap to see if the results are still different?

Nevertheless, I will try your dataset on both systems to verify, but the links you sent are not valid. Could you please send them privately at **daniele.oxoli@polimi.it**? I will also need info about the precise setting you used on both QGIS and ArcMap (e.g. n. of permutations, type of weights used, the distance used, etc.)

Thank you in advance and I'll be back to you asap

Daniele
