### ISSUE TITLE
(oups) Where is the menu ?

### ISSUE THREAD

**Issue by vincentv70** [danioxoli/HotSpotAnalysis_Plugin#30]
I use QGIS 3.6.3 under win10. I have followed the advise of Daniele for py command script in OSGeo4W shell as administrator. 

But, the installation of the plugins failed :
ModuleNotFoundError: ModuleNotFoundError: No module named 'pysal.esda' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/vincent/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/vincent/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 39, in 
    from pysal.esda.getisord import *
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pysal.esda'No module named 'pysal.esda' 

Plus, this kind of message:
:/PROGRA~1/QGIS3~1.6/apps/qgis/plugins/grassplugin7.dll (Impossible de charger la bibliothèque C:\PROGRA~1\QGIS3~1.6\apps\qgis\plugins\grassplugin7.dll 

Is there a simple way for a non-geomatician to solve this (possible) inconsistency of path ?

Gratefully yours.
vincent

**Comment by danioxoli** [comment]
Dear Vincent,

Which PySAL version are you using? The problem is due to that.

Run `python -m pip show pysal` for checking it. If the installed version is higher or equal than 2.0, type `python -m pip install -I pysal==1.14.3` (See readme file of the branch [qgis3](https://github.com/danioxoli/HotSpotAnalysis_Plugin/commits/qgis3) )

Alternatively, I've started to develop a plugin version to be used with PySAL 2. You may try to install [this one](https://github.com/danioxoli/HotSpotAnalysis_Plugin/tree/qgis3pysal2) instead of downgrading PySAL (I had not tested exhaustively the PySAL 2... so success is not guaranteed)


Best,

Daniele
