### ISSUE TITLE
Select the Attribute field!

### ISSUE THREAD

**Issue by blinters** [danioxoli/HotSpotAnalysis_Plugin#40]
[](url)
![image](https://user-images.githubusercontent.com/15936817/67183893-1d070280-f415-11e9-9dfd-b70a4cdc8c7c.png)

Hi, in the hotspot analysis tool, what should we select for the "select for attribute field"? what kind of attribute needs to be provided?

look forward to your reply

**Comment by danioxoli** [comment]
Hello,

Both Moran's and Getis-Ord local stats are designed to test the spatial association of continuous numerical variables. Therefore, the attribute field you select must contain observations from the variable to which your analysis is designed for.  If you need examples, you can find something here:
https://re.public.polimi.it/retrieve/handle/11311/1040664/249578/oxoli_et_al_geam2017.pdf

Please, be careful that there must be no empty values in the numeric attribute field you selected as well as the selected field must exist in your input shapefile attribute table. No virtual fields (e.g. from join operations) are allowed.

Thanks for your interest

Best,
Daniele

**Comment by blinters** [comment]
Hi Daniele,

Thanks for the prompt reply! My intention is to find hotspot purely based on bicycle rider GPS lat,lon coordinates, for example, riders returning bicycle to a sharing stations/points. What would you recommend my attribute field to be? You would see that my point data is really raw and only have lat, lon coordinates.

Look forward to your reply

**Comment by danioxoli** [comment]
Actually, 

if you need to use Moran's or Getis-Ord you must aggregate your data - e.g. on a grid - and associate to each grid cell the count of poor lat|lon points falling inside. Then, you can use the count as a variable to run the plugin. Please, find an example here: 
https://re.public.polimi.it/retrieve/handle/11311/1010654/172465/isprs-archives-XLI-B2-603-2016.pdf

There are many options for aggregating data and the choice is generally arbitrary. However, the aggregation unit dimension and shape have to be defined accordingly to the scale of your analysis in order to avoid as much as possible the typical problems of [aggregated data analysis](https://en.wikipedia.org/wiki/Ecological_fallacy) (you can find plenty of examples in the literature).

Other exploratory techniques are available, such as heatmaps or similar. Concerning spatial association statistics, for binary variables, the most popular one is the Local Join Count. For testing it, you may go outside QGIS and get practice with e.g. [GeoDa](https://geodacenter.github.io/index.html) (strongly suggested).

Hope this will be helpful!

Daniele
