### ISSUE TITLE
No icon showing on toolbar 

### ISSUE THREAD

**Issue by GeoDaemon** [danioxoli/HotSpotAnalysis_Plugin#5]
Hi- I installed the plugin using the zip folder. Successfully installed the plugin in but icon not showing on the toolbar.

**Comment by danioxoli** [comment]
Hi,

Actually, the space for the icon in the tab is allocated but the picture is not displayed
![schermata 2018-05-23 alle 10 56 41](https://user-images.githubusercontent.com/15163569/40414854-b160cba6-5e79-11e8-8b45-718f4be59a25.png)

I will try to figure out what's the problem because I did not touch the icon in migrating on QGIS3 and that's should be the issue. Thank you for notice!

Daniele

**Comment by danioxoli** [comment]
Hi,

The issue should be solved on the latest qgis3 branch repo.

Best,

Daniele
