### ISSUE TITLE
Error with plug-in

### ISSUE THREAD

**Issue by KlaasLo** [danioxoli/HotSpotAnalysis_Plugin#54]
Hi,

I'm really interested in the plug-in, but I have some issues setting it up. I'm pretty far I think, but the following error shows.

WARNING    Traceback (most recent call last):
              File "C:/Users/KlaasLo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 546, in run
              layers, layers_shp = self.loadLayerList()
             TypeError: cannot unpack non-iterable NoneType object

I would love to know what to do, thanks in advance.

**Comment by danioxoli** [comment]
Hello,

This looks like an issue due to the input layer. 
Try to use a projected shapefile (points or polygons) with associated at least a numeric field with no missing data. No other format is currently accepted. Moreover the numeric filed should be stored in the attribute table of the shapefile, no virtual fields (e.g. resulting from a join operation) should be used. 

Finally, place this layer at the top of the layer panel and open the plugin. In the case of a layer without the above characteristics is found in the first position of the layer panel this may cause errors (this is a known bug I will try to fix asap).

let me know if this was helpful!

best,

Daniele

**Comment by belisards** [comment]
Thanks, it worked for me!
